apiVersion: v1
kind: Service
metadata:
  name: geo-fence
  labels:
    app: geo-fence
spec:
  type: ClusterIP
  selector:
    app: geo-fence
  ports:
  - name: geo-fence
    port: 8000
    targetPort: 8000

